apiVersion: v1
kind: Service
metadata:
  name: {{ include "odrl-pap.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{ include "odrl-pap.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.deployment.odrlPap.port }}
      protocol: TCP
      name: {{ include "odrl-pap.fullname" . }}
  selector:
    {{ include "odrl-pap.labels" . | nindent 4 }}