---
apiVersion: v1
kind: Service
metadata:
  name: opa
  labels:
    app.kubernetes.io/name: opa
    app.kubernetes.io/instance: opa
spec:
  type: LoadBalancer
  ports:
    - port: 8181
      targetPort: 8181
      protocol: TCP
      name: opa
  selector:
    app.kubernetes.io/name: opa
    app.kubernetes.io/instance: opa
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opa
  labels:
    app.kubernetes.io/name: opa
    app.kubernetes.io/instance: opa
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: opa
      app.kubernetes.io/instance: opa
  template:
    metadata:
      labels:
        app.kubernetes.io/name: opa
        app.kubernetes.io/instance: opa
    spec:
      serviceAccountName: default
      containers:
        - name: opa
          imagePullPolicy: IfNotPresent
          image: "openpolicyagent/opa:0.62.1"
          ports:
            - name: http
              containerPort: 8181
              protocol: TCP
          args:
            - "run"
            - "--ignore=.*"  # exclude hidden dirs created by Kubernetes
            - "--server"