apiVersion: v1
kind: Service
metadata:
  name: {{ include "opa.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{ include "opa.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.deployment.opa.port }}
      protocol: TCP
      name: {{ include "opa.fullname" . }}
  selector:
    {{ include "opa.labels" . | nindent 4 }}