apiVersion: v2
name: postgresql
description: Dependency chart
type: application
version: 0.0.1
appVersion: 0.0.1

dependencies:
  - name: postgresql
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 13.1.5