openapi: 3.0.3
info:
  title: OPA Bundle API
  description: OPA Bundle API
  version: 0.63.0
paths:
  /bundles/service/v1/policies.tar.gz:
    get:
      operationId: getPolicies
      summary: Return the policies bundle.
      responses:
        '200':
          description: The tar.gz containing the policies.
          content:
            application/octect-stream:
              schema:
                type: string
                format: binary
  /bundles/service/v1/methods.tar.gz:
    get:
      operationId: getMethods
      summary: Return the methods bundle.
      responses:
        '200':
          description: The tar.gz containing the methods.
          content:
            application/octect-stream:
              schema:
                type: string
                format: binary
  /bundles/service/v1/data.tar.gz:
    get:
      operationId: getData
      summary: Return the additional data to be used for policy evaluation.
      responses:
        '200':
          description: The tar.gz containing the data.
          content:
            application/octect-stream:
              schema:
                type: string
                format: binary