openapi: 3.0.3
info:
  title: ODRL PAP
  description: ODRL PAP
  version: 1.0.0
paths:
  /policy:
    post:
      operationId: createPolicy
      summary: Creates a new policy from the given odrl-json
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OdrlPolicyJson'
      responses:
        '200':
          description: The rego policy
          content:
            text/plain:
              schema:
                type: string
          headers:
            Location:
              schema:
                type: string
              description: location of the created policy
  /policy/{id}:
    put:
      parameters:
        - $ref: '#/components/parameters/Id'
      operationId: createPolicyWithId
      summary: Creates or overwrites the given policy.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OdrlPolicyJson'
      responses:
        '200':
          description: The rego policy
          content:
            text/plain:
              schema:
                type: string
          headers:
            Location:
              schema:
                type: string
              description: location of the created policy
        '409':
          description: Should be returned in case the policy is not allowed to be modified
    get:
      parameters:
        - $ref: '#/components/parameters/Id'
      summary: Return the given policy by its ID.
      operationId: getPolicyById
      responses:
        '200':
          description: Successfully retrieved the policy.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Policy'
        '404':
          description: No such policy exists
    delete:
      parameters:
        - $ref: '#/components/parameters/Id'
      summary:  Delete the given policy.
      operationId: deletePolicyById
      responses:
        '204':
          description: Policy was successfully removed.
        '404':
          description: No such policy exists


components:
  parameters:
    Id:
      name: id
      in: path
      required: true
      schema:
        $ref: '#/components/schemas/Uid'
  schemas:
    Policy:
      type: object
      properties:
        id:
          type: string
        odrl:
          type: string
        rego:
          type: string
    Uid:
      type: string
      format: https://datatracker.ietf.org/doc/html/rfc3987
    OdrlPolicyJson:
      type: object
      additionalProperties: true